# Generated by Django 6.0 on 2025-12-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Naam van de concurrent (bijv. 'Ziggo')", max_length=200)),
                ('url', models.URLField(help_text="URL om te monitoren (bijv. 'https://ziggo.nl/internet')", max_length=500)),
                ('interval', models.IntegerField(choices=[(5, '5 minuten'), (15, '15 minuten'), (30, '30 minuten'), (60, '1 uur')], default=15, help_text='Hoe vaak scannen we deze target?')),
                ('status', models.CharField(choices=[('active', 'Actief'), ('paused', 'Gepauzeerd')], default='active', help_text='Is deze target actief?', max_length=10)),
                ('last_hash', models.CharField(blank=True, help_text='MD5 hash van laatste scan (voor change detection)', max_length=32, null=True)),
                ('last_scan_at', models.DateTimeField(blank=True, help_text='Wanneer was de laatste scan?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_path', models.CharField(help_text="Pad naar screenshot bestand (bijv. '/storage/screenshots/abc123.png')", max_length=500)),
                ('content_hash', models.CharField(help_text='MD5 hash van pagina content (tekst + image URLs)', max_length=32)),
                ('analysis_json', models.JSONField(blank=True, help_text='Gestructureerde analyse van Gemini (type, title, summary, etc.)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Bezig'), ('success', 'Succesvol'), ('failed', 'Mislukt')], default='pending', help_text='Status van deze scan', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error bericht als scan is mislukt', null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, help_text='Wanneer is deze scan uitgevoerd?')),
                ('target', models.ForeignKey(help_text='Welke target is gescand?', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='shared.target')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['-scanned_at'], name='shared_scan_scanned_6352f7_idx'), models.Index(fields=['target', '-scanned_at'], name='shared_scan_target__a44f94_idx')],
            },
        ),
    ]
