# Generated by Django 6.0 on 2025-12-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Verzonden'), ('failed', 'Mislukt')], default='sent', max_length=10)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='shared.scan')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
